import 'server-only'
import './globals.css'
import { GAScript, GABody} from '../utils/Google/analytics/google-analytics'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MyNavbar from '@/components/navbar'
import Footer from './footer'
import { config } from '@fortawesome/fontawesome-svg-core'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faFontAwesome } from '@fortawesome/free-brands-svg-icons'
import { fas } from '@fortawesome/free-solid-svg-icons'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { AuthContextProvider } from '../utils/context/AuthContext'
config.autoAddCss = false
library.add(fas, faFontAwesome)

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{scrollBehavior:'smooth'}}>
      <GAScript/>
<body className="mx-auto overscroll-auto no-scrollbar">
  <GABody/>
      
      <video muted autoPlay loop className="fixed scale-[1.6] z-0 invisible md:visible top-0 min-h-screen">         
    <source src="https://video.wixstatic.com/video/11062b_d013b164dadb47ec8e746ab178aacfbb/1080p/mp4/file.mp4" type="video/mp4"/>       
</video>
<AuthContextProvider>
        <main className="relative min-w-screen">
          <MyNavbar/>
          {children}
          </main>
          </AuthContextProvider>
          <Footer/>
      </body>
    </html>
  )
}
